#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

prog=/usr/local/bin/run-geoipupdate

${prog}

if [ ! -f /root/crontabs/root ]; then
  mkdir -p /root/crontabs
  echo "${SCHEDULE} ${prog}" > /root/crontabs/root
fi

exec crond -f -c /root/crontabs
